export interface Subject {
  id: string;
  label: string;
  color: string;
  type: "tyt" | "ayt";
  topics: string[];
}

export const SUBJECTS: Subject[] = [
  // ─── TYT ─────────────────────────────────────────────────────────────────
  {
    id: "turkce",
    label: "Türkçe",
    color: "#f59e0b",
    type: "tyt",
    topics: [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragrafta Anlam",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcük Türleri",
      "Fiiller",
      "Fiilimsiler",
      "Sözcükte Yapı ve Ekler",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozuklukları",
    ],
  },
  {
    id: "tyt_matematik",
    label: "Matematik",
    color: "#8b5cf6",
    type: "tyt",
    topics: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme Kuralları",
      "EBOB - EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran ve Orantı",
      "Denklem Çözme",
      "Problemler",
      "Kümeler",
      "Kartezyen Çarpım",
      "Mantık",
      "Fonksiyonlar",
      "Polinomlar",
      "İkinci Dereceden Denklemler",
      "Permütasyon, Kombinasyon, Olasılık",
      "Veri ve İstatistik",
    ],
  },
  {
    id: "tyt_geometri",
    label: "Geometri",
    color: "#6366f1",
    type: "tyt",
    topics: [
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Dik ve Özel Üçgenler",
      "Dik Üçgende Trigonometrik Bağıntılar",
      "İkizkenar ve Eşkenar Üçgen",
      "Üçgende Açıortay ve Kenarortay",
      "Üçgende Eşlik ve Benzerlik",
      "Üçgende Alan",
      "Üçgende Açı - Kenar Bağıntıları",
      "Çokgenler",
      "Dörtgenler ve Özel Dörtgenler",
      "Çemberde Açı ve Uzunluk",
      "Dairede Çevre ve Alan",
      "Katı Cisimler",
      "Analitik Geometri",
    ],
  },
  {
    id: "tyt_fizik",
    label: "Fizik",
    color: "#06b6d4",
    type: "tyt",
    topics: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Hareket ve Kuvvet",
      "İş, Güç ve Enerji",
      "Isı, Sıcaklık ve Genleşme",
      "Elektrostatik",
      "Elektrik Akımı ve Devreler",
      "Manyetizma",
      "Basınç",
      "Kaldırma Kuvveti",
      "Dalgalar",
      "Optik",
    ],
  },
  {
    id: "tyt_kimya",
    label: "Kimya",
    color: "#10b981",
    type: "tyt",
    topics: [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Hâlleri",
      "Doğa ve Kimya",
      "Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar",
      "Karışımlar",
      "Asitler, Bazlar ve Tuzlar",
      "Kimya Her Yerde",
    ],
  },
  {
    id: "tyt_biyoloji",
    label: "Biyoloji",
    color: "#84cc16",
    type: "tyt",
    topics: [
      "Yaşam Bilimi Biyoloji",
      "Hücre ve Organelleri",
      "Canlıların Dünyası",
      "Hücre Bölünmeleri",
      "Kalıtımın Genel İlkeleri",
      "Ekosistem Ekolojisi ve Güncel Çevre Sorunları",
    ],
  },
  {
    id: "tarih",
    label: "Tarih",
    color: "#ef4444",
    type: "tyt",
    topics: [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ'da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti ve Medeniyeti",
      "Dünya Gücü Osmanlı",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi",
      "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Millî Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
    ],
  },
  {
    id: "cografya",
    label: "Coğrafya",
    color: "#14b8a6",
    type: "tyt",
    topics: [
      "Doğa ve İnsan",
      "Dünya'nın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "Harita Bilgisi",
      "İklim Bilgisi",
      "Dünya'nın Tektonik Oluşumu, İç ve Dış Kuvvetler",
      "Su, Toprak ve Bitki Varlığı",
      "Nüfus, Göç ve Yerleşme",
      "Türkiye'nin Nüfusu ve Yerleşmesi",
      "Ekonomik Faaliyetler",
      "Bölgeler ve Ülkeler",
      "Doğal Afetler",
    ],
  },
  {
    id: "felsefe",
    label: "Felsefe",
    color: "#a78bfa",
    type: "tyt",
    topics: [
      "Felsefeyi Tanıma",
      "Felsefeyle Düşünme",
      "Varlık Felsefesi",
      "Bilgi Felsefesi",
      "Bilim Felsefesi",
      "Ahlak Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Sanat Felsefesi",
      "Felsefe Tarihi",
    ],
  },
  {
    id: "din",
    label: "Din Kültürü",
    color: "#fb7185",
    type: "tyt",
    topics: [
      "İnanç",
      "İbadet",
      "Ahlak ve Değerler",
      "Din, Kültür ve Medeniyet",
      "Hz. Muhammed",
      "Vahiy ve Akıl",
      "İslam Düşüncesinde Yorumlar",
    ],
  },

  // ─── AYT Sayısal ─────────────────────────────────────────────────────────
  {
    id: "ayt_matematik",
    label: "Matematik",
    color: "#6366f1",
    type: "ayt",
    topics: [
      "Fonksiyonlarda Uygulamalar",
      "İkinci Dereceden Fonksiyonlar ve Grafikleri",
      "İkinci Dereceden İki Bilinmeyenli Denklem Sistemleri",
      "İkinci Dereceden Eşitsizlikler ve Eşitsizlik Sistemleri",
      "Karmaşık Sayılar",
      "Logaritma",
      "Diziler",
      "Trigonometri",
      "Limit ve Süreklilik",
      "Türev",
      "İntegral",
      "Permütasyon, Kombinasyon, Binom, Olasılık",
    ],
  },
  {
    id: "ayt_geometri",
    label: "Geometri",
    color: "#8b5cf6",
    type: "ayt",
    topics: [
      "Üçgenler (İleri Düzey)",
      "Çokgenler ve Dörtgenler",
      "Katı Cisimler",
      "Çember ve Daire (İleri Düzey)",
      "Doğrunun Analitik İncelenmesi",
      "Çemberin Analitik İncelenmesi",
      "Dönüşüm Geometrisi",
    ],
  },
  {
    id: "ayt_fizik",
    label: "Fizik",
    color: "#06b6d4",
    type: "ayt",
    topics: [
      "Vektörler",
      "Bağıl Hareket",
      "Newton'un Hareket Yasaları",
      "Bir Boyutta Sabit İvmeli Hareket (Atışlar)",
      "İki Boyutta Hareket",
      "Enerji ve Hareket",
      "İtme ve Çizgisel Momentum",
      "Tork",
      "Denge ve Kütle Merkezi",
      "Basit Makineler",
      "Elektriksel Kuvvet ve Elektrik Alan",
      "Elektriksel Potansiyel",
      "Düzgün Elektrik Alan ve Sığa",
      "Manyetizma ve Elektromanyetik İndüklenme",
      "Alternatif Akım",
      "Transformatörler",
      "Çembersel Hareket",
      "Dönerek Öteleme Hareketi ve Açısal Momentum",
      "Kütle Çekim Kuvveti ve Kepler Yasaları",
      "Basit Harmonik Hareket",
      "Dalga Mekaniği",
      "Atom Fiziğine Giriş ve Radyoaktivite",
      "Modern Fizik",
      "Modern Fiziğin Teknolojideki Uygulamaları",
    ],
  },
  {
    id: "ayt_kimya",
    label: "Kimya",
    color: "#10b981",
    type: "ayt",
    topics: [
      "Modern Atom Teorisi",
      "Gazlar",
      "Sıvı Çözeltiler ve Çözünürlük",
      "Kimyasal Tepkimelerde Enerji",
      "Kimyasal Tepkimelerde Hız",
      "Kimyasal Tepkimelerde Denge",
      "Asit-Baz Dengesi",
      "Çözünürlük Dengesi",
      "Kimya ve Elektrik",
      "Karbon Kimyasına Giriş",
      "Organik Kimya",
      "Enerji Kaynakları ve Bilimsel Gelişmeler",
    ],
  },
  {
    id: "ayt_biyoloji",
    label: "Biyoloji",
    color: "#84cc16",
    type: "ayt",
    topics: [
      "Sinir Sistemi",
      "Endokrin Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım ve Lenf Sistemi",
      "Bağışıklık Sistemi",
      "Solunum Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Komünite ve Popülasyon Ekolojisi",
      "Genden Proteine",
      "Canlılarda Enerji Dönüşümleri",
      "Bitki Biyolojisi",
      "Canlılar ve Çevre",
    ],
  },
];

export const SUBJECT_MAP = Object.fromEntries(SUBJECTS.map((s) => [s.id, s]));
export const SUBJECT_COLORS = Object.fromEntries(SUBJECTS.map((s) => [s.id, s.color]));
